# Generated by Django 5.2.3 on 2025-07-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
