# Generated by Django 5.2.3 on 2025-06-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_producttag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name_plural': 'Product Tags'},
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='product.producttag'),
        ),
    ]
