# Generated by Django 5.2.3 on 2025-07-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_producttag_options_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
    ]
