# Generated by Django 5.2.4 on 2025-08-10 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0008_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
